# Generated by Django 5.1.1 on 2025-02-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookWorldApp', '0002_paymentmodel_delete_paymentaccept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentModel',
        ),
    ]
